spring:
  datasource:
    username: root
    password: root 
    url: jdbc:mysql://localhost:3306/db_zenxl?createDatabaseIfNotExist=true&autoReconnect=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL8Dialect  
    
  mail:  
    host: smtp.gmail.com
    username: zenxldemo@gmail.com
    password: jhufqshagfrcsgwz
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    csrf:
      enabled: true
         
  
item:
    upload: C:\zenxl-files\item
    
import:
    upload: C:\zenxl-files\import
    
export:
    upload: C:\zenxl-files\export
    
